SELECT EMPLOYEE_ID, ROWID, ROWNUM, DBMS_ROWID.ROWID_ROW_NUMBER(ROWID) AS ROWNUMBER,
                                   DBMS_ROWID.ROWID_BLOCK_NUMBER(ROWID) AS BLOCK_NUMBER,
                                   DBMS_ROWID.ROWID_OBJECT(ROWID) AS OBJECT, 
                                   DBMS_ROWID.ROWID_RELATIVE_FNO(ROWID) AS "FILE"
FROM DEMO8
/
