SELECT EMPLOYEE_ID, ROWID, ROWNUM, DBMS_ROWID.ROWID_ROW_NUMBER(D.ROWID) AS ROWNUMBER,
                                   DBMS_ROWID.ROWID_BLOCK_NUMBER(D.ROWID) AS BLOCK_NUMBER,
                                   OBJECT_NAME AS OBJECT,
                                   DBMS_ROWID.ROWID_RELATIVE_FNO(D.ROWID) AS "FILE"
FROM DEMO8 D
JOIN USER_OBJECTS ON (DBMS_ROWID.ROWID_OBJECT(D.ROWID) = OBJECT_ID)
/
